### ISSUE TITLE
Fail on provision

### ISSUE THREAD

**Issue by kucrut** [Chassis/v8js#36]
1. What operating system do you use?
macOS

2. What version of Vagrant are you running?
2.2.6

3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
See https://www.altis-dxp.com/resources/docs/local-chassis/

5. Do you have any Chassis other extensions installed? If so, what are they?
See https://www.altis-dxp.com/resources/docs/local-chassis/

I'm getting this error when provisioning Altis' local sever:

```
==> site.local: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install libv8-7.5' returned 100: Reading package lists...
==> site.local: Building dependency tree...
==> site.local: Reading state information...
==> site.local: E: Unable to locate package libv8-7.5
==> site.local: E: Couldn't find any package by glob 'libv8-7.5'
==> site.local: E: Couldn't find any package by regex 'libv8-7.5'
==> site.local: Error: /Stage[main]/V8js::Extension/Package[libv8-7.5]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install libv8-7.5' returned 100: Reading package lists...
```

**Comment by kucrut** [comment]
Please note that after the initial provision finished, running `vagrant provision` again "fixes" it.

**Comment by BronsonQuick** [comment]
I can replicate this. I am pretty sure I know a fix as well.
